version: '3.8'

services:
  cryptosage:
    build: .
    container_name: cryptosage_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./app.py:/app/app.py
    restart: unless-stopped
